server:
  port: 8080

spring:
  application:
    name: git-pulling-app

springdoc:
  swagger-ui:
    path: /swagger-ui.yaml

app:
  github:
    url: https://api.github.com
    token: ${GIT_API_TOKEN}
    version: 2022-11-28
