openapi: 3.0.1
info:
  title: Github metadata pulling app
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local
paths:
  /api/github/{username}/repositories:
    get:
      summary: Get public user repositories info that are not forks
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
        - name: Accept
          in: header
          required: true
          schema:
            type: string
            default: application/json
      responses:
        '200':
          description: List of repositories that are not forks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RepositoryDto'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '406':
          description: Not Acceptable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    RepositoryDto:
      type: object
      properties:
        repositoryName:
          type: string
        ownerLogin:
          type: string
        branches:
          type: array
          items:
            $ref: '#/components/schemas/BranchDto'
    BranchDto:
      type: object
      properties:
        name:
          type: string
        lastCommitSha:
          type: string
    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string